export const intentType = {
    QUERY_BALANCE: "QUERY_BALANCE",
    TRANSFER: "TRANSFER",
    QUERY_POOLS: "QUERY_POOLS",
    DEPOSIT: "DEPOSIT",
    QUERY_PORTFOLIO: "QUERY_PORTFOLIO",
    WITHDRAW: "WITHDRAW",
    OTHER: "OTHER"
};